ECHO OFF
CLS

CALL "Release\test.exe" "E:\AIIF\SegAll\CONOCIMIENTO\UNIVERSIDAD\TESIS\P_NUEVO\APLICACIONES\TLAB\DSP_LAB\MAT_IO\zip_utils_src\examples\test\simple1.zip" "E:\AIIF\SegAll\CONOCIMIENTO\UNIVERSIDAD\TESIS\P_NUEVO\APLICACIONES\TLAB\DSP_LAB\MAT_IO\zip_utils_src\examples\test\z"
CALL "Release\test.exe" "E:\AIIF\SegAll\CONOCIMIENTO\UNIVERSIDAD\TESIS\P_NUEVO\APLICACIONES\TLAB\DSP_LAB\MAT_IO\zip_utils_src\examples\test\simple2.zip" "E:\AIIF\SegAll\CONOCIMIENTO\UNIVERSIDAD\TESIS\P_NUEVO\APLICACIONES\TLAB\DSP_LAB\MAT_IO\zip_utils_src\examples\test\z"
pause